# config.py

MONGODB_URI = "mongodb://PCL_Interns_admin:PCLinterns2050admin@172.191.245.199:27017/PCL_Interns"
DATABASE_NAME = "PCL_Interns"
GOALS_COLLECTION_NAME = "GOL_PerformanceGoals"
ELIGIBILITY_PROFILES_COLLECTION_NAME = "EligibilityProfiles"
REVIEW_PERIOD_COLLECTION_NAME = "GOL_ReviewPeriod"
INCLUDE_EXCLUDE_COLLECTION_NAME = "GOL_include_exclude"
GOAL_PLAN_COLLECTION_NAME = "GOL_GoalPlans"
