

MONGODB_URI = "mongodb://PCL_Interns_admin:PCLinterns2050admin@172.191.245.199:27017/PCL_Interns"
DATABASE_NAME = "PCL_Interns"
ELIGIBILITY_PROFILE_COLLECTION_NAME = "P_EligibilityProfiles"
ELIGIBILITY_BATCH_PROCESS_COLLECTION_NAME = "P_EligibilityBatchProcess"
REVIEW_PERIOD_COLLECTION_NAME = "P_ReviewPeriods"
PERFORMANCE_ROLE_COLLECTION_NAME = "P_PerformanceRoles"
PERFORMANCE_DOCUMENT_TYPE_COLLECTION_NAME = "P_PerformanceDocumentTypes"
FEEDBACK_TEMPLATE_COLLECTION_NAME = "P_FeedbackTemplates" 
PERFORMANCE_PROCESS_FLOW_COLLECTION_NAME = "P_PerformanceProcessFlows"
CHECK_IN_TEMPLATE_COLLECTION_NAME = "P_CheckInTemplates"
QUESTIONNAIRE_COLLECTION_NAME = "P_Questionnaires"
PERFORMANCE_TEMPLATE_COLLECTION_NAME = "P_PerformanceTemplates"
MY_PERFORMANCE_COLLECTION_NAME = "P_Performance_document"                                        
EMPLOYEE_DETAILS_COLLECTION_NAME = "s_employeedetails_2"
GOAL_PLANS_COLLECTION_NAME = "GOL_GoalPlans"
PERFORMANCE_TEMPLATE_CONNECTION_COLLECTION_NAME = "P_Performance_template_connection"






