openapi: 3.1.0
info:
  title: Employee Course Assignment API
  description: API for assigning courses to employees based on job changes.
  version: 1.0.0
servers:
  - url: https://fusionobjects.com
    description: Main API server for course assignments

paths:
  /assign_course:
    post:
      operationId: assignCourses
      summary: Assigns courses to employees based on recent job changes.
      responses:
        "200":
          description: Courses assigned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Courses assigned successfully.
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Employee:
      type: object
      properties:
        Person_Number:
          type: string
        First_Name:
          type: string
        Last_Name:
          type: string
        Job_Code:
          type: string
        Effective_Start_Date:
          type: string
          format: date-time
        Effective_End_Date:
          type: string
          format: date-time
    Course:
      type: object
      properties:
        Course_Name:
          type: string
        Due_Date:
          type: string
          format: date

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

security:
  - bearerAuth: []
