openapi: 3.1.0
info:
  title: Email Notification API
  description: API to send email notifications with dynamic templates and attachments.
  version: 1.0.0
servers:
  - url: https://fusionobjects.com
    description: Main API server for email notifications

paths:
  /send_email:
    post:
      operationId: sendEmail
      summary: Sends an email notification with the specified parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                  description: Subject of the email
                recipient_name:
                  type: string
                  description: Name of the recipient
                recipient_email:
                  type: string
                  format: email
                  description: Email address of the recipient
                company_email:
                  type: string
                  format: email
                  description: Company email address to send from
                event:
                  type: string
                  description: Event name to fetch the email template
                dynamic_params:
                  type: object
                  additionalProperties:
                    type: string
                  description: Dynamic parameters to render in the email template
                attachments:
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                        description: Path to the attachment file
                      filename:
                        type: string
                        description: Name of the attachment file
                      content_type:
                        type: string
                        description: Content type of the attachment file
      responses:
        "200":
          description: Email sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
        "500":
          description: Failed to send email.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
