openapi: 3.1.0
info:
  title: Goal Assignment API
  description: API for assigning goals to employees based on eligibility criteria.
  version: 1.0.0
servers:
  - url: https://fusionobjects.com
    description: Main API server for goal assignment

paths:
  /assign_goal:
    post:
      operationId: assignGoal
      summary: Assigns a goal to eligible employees based on the provided eligibility profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Goal_Name
                - Eligibility_Profile_Name
              properties:
                Goal_Name:
                  type: string
                  description: Name of the goal to be assigned.
                Eligibility_Profile_Name:
                  type: string
                  description: Name of the eligibility profile to use for assigning the goal.
      responses:
        "200":
          description: Goal successfully assigned to eligible employees.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Assigned {goal_name} to eligible employees
        "400":
          description: Invalid request data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Goal_Name and Eligibility_Profile_Name are required
        "404":
          description: Goal, eligibility profile, or eligible employees not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      GoalNotFound:
                        summary: Goal not found
                        value: Goal not found
                      EligibilityProfileNotFound:
                        summary: Eligibility profile not found
                        value: Eligibility profile not found
                      NoEligibleEmployees:
                        summary: No eligible employees found
                        value: No eligible employees found
